config/routes.rb
ToDoApp::Application.routes.draw do
  resources :todos

  devise_for :users

  root :to => "todos#index"

  resources :dashboard

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :priority
  has_many :todos

  validates :name, :presence => true
  validates :priority, :presence => true, :numericality => true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :content, :deadline, :status, :title, :user_id
  belongs_to :category

  validates :title, :presence => true
  validates :content, :presence => true
  validates_inclusion_of :status, :in => %w( entered started done dropped failed ),
  						 :message => "extension %{value} is not included in the list of statuses"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :authenticate_user!

	def index
		
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			redirect_to :controller => 'todos', :action => 'index'
		end
	end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_filter :authenticate_user!

  # GET /todos
  # GET /todos.json
  def index
    # these two at the top because they both return an ActiveRecord Object
    @todos = Todo.where(:user_id => current_user.id)
    @todos = @todos.paginate(:page => params[:page], :per_page => 5)
    
    # the following returns an Array
    @todos = @todos.find(:all, :include => :category, :order => "categories.priority")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = Todo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    params[:todo][:user_id] = current_user.id
    @todo = Todo.new(params[:todo].except(:category))

    handle_category(params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render json: @todo, status: :created, location: @todo }
      else
        format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def handle_category(params)
    my_category = Category.where(params[:todo][:category])

    if my_category.count > 0
      unless @todo.category.map(&:id).include?(my_category[0].id)
        @todo.category = my_category[0]
      end
    else
      @todo.category = Category.create(params[:todo][:category])
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])
    params[:todo][:user_id] = current_user.id
    respond_to do |format|
      if @todo.update_attributes(params[:todo].except(:category)) && @todo.category.update_attributes(params[:todo][:category])
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/categories/_form.html.erb
<%= form.fields_for :category do |c| %>
  <div class="field">
      <%= c.label :name %><br />
      <%= c.text_field :name %>
  </div>
  <div class="field">
      <%= c.label :priority %><br />
      <%= c.number_field :priority %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Priority</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.priority %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Priority:</b>
  <%= @category.priority %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/dashboard/index.html.erb
<h1>Welcome to your dashboard.</h1>

app/views/home/index.html.erb
<h1>Welcome to our website.</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "bootstrap.min", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap-dropdown" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="navbar navbar-inverse">
		  <div class="navbar-inner">
		    <div class="container">
		      <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </a>
		      <a class="brand" href="#">To Do App @ CloudFactory</a>
		      <div class="nav-collapse collapse navbar-responsive-collapse">
		        <ul class="nav">
		          <li class="active"><%= link_to 'Home', todos_path %></li>
		        </ul>
		        
		        <form class="navbar-search pull-left" action="">
		          <input type="text" class="search-query span2" placeholder="Search">
		        </form>

		        <ul class="nav pull-right">
					<% if user_signed_in? %>
						<li><a href="#">Welcome, <%= current_user.email %></a></li>
						<li class="divider-vertical"></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
								<li class="divider"></li>
								<li><a href="#">Other settings</a></li>
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign up", new_user_registration_path %></li>
						<li><a href="#">/</a></li>
						<li><%= link_to "Sign in", new_user_session_path %></li>
					<% end %>
		        </ul>
		      </div><!-- /.nav-collapse -->
		    </div>
		  </div><!-- /navbar-inner -->
		</div>
	</header>

	<div class="container-fluid">
		<div class="row-fluid">
			<%= yield %>
		</div>
	</div>

	<footer class="footer">
	      <div class="container">
	        <p>Copyright &copy; 2013. Uzzal Devkota and Milan Thapa.</p>
	      </div>
	</footer>
	<script type="text/javascript">
		$('dropdown-toggle').dropdown()
	</script>
</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content, :rows => 7 %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <% select_options = [['entered', 'entered'], ['started', 'started'], ['done', 'done'], ['dropped', 'dropped'], ['failed', 'failed']] %>
    <%= f.select(:status, options_for_select(select_options)) %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br />
    <%= f.date_select :deadline %>
  </div>

  <h2>Category</h2>
  <%= render :partial => 'categories/form',
              :locals => {:form => f} %>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>My ToDos</h1>

<table class="table">
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Status</th>
    <th>Deadline</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= link_to todo.title, todo %>
    <td><%= todo.content %></td>
    <td><%= todo.status %></td>
    <td><%= todo.deadline.to_formatted_s(:short) %></td>
    <td>
      <%= link_to(edit_todo_path(todo)) do %>
        <i class="icon-edit"></i>
      <% end %>
    </td>
    <td>
      <%= link_to todo, :method => :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="icon-trash"></i>
      <% end %>
    </td>
  </tr>
<% end %>
</table>
  <%= will_paginate @posts %>
<br />

<%= link_to 'New Todo', new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @todo.title %>
</p>

<p>
  <b>Content:</b>
  <%= @todo.content %>
</p>

<p>
  <b>Status:</b>
  <%= @todo.status %>
</p>

<p>
  <b>Deadline:</b>
  <%= @todo.deadline %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

<h3>Category</h3>

<p><%= @todo.category.name %>(<%= @todo.category.priority %>)</p>